mailhog:
  enabled: true


image:
  repository:
  pullPolicy: Always
  tag: ""

imagePullSecrets:
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 400m
    memory: 1024Mi