localstack:
  enabled: true
  startServices: kinesis,dynamodb,cloudwatch,s3
  enableStartupScripts: true
  startupScriptContent: |
    awslocal s3 mb s3://avail-customer-logos-local

dynamodb:
  endpoint:
    
image:
  repository:
  pullPolicy: Always
  tag: ""

imagePullSecrets:
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  
resources:
  requests:
    cpu: 200m
    memory: 512Mi