apiVersion: v1
kind: Service
metadata:
  name: avail-postgresql
  namespace: backend-abattu
  labels:
    app: avail-postgresql
spec:
  selector:
    app: avail-postgresql
  type: ClusterIP
  ports:
    - name: service
      port: 5432
      protocol: TCP